In [51]:
import pandas as pd
from simpledbf import Dbf5
pd.set_option('display.max_columns', 100)
from pymystem3 import Mystem
from nltk.stem import SnowballStemmer
russian_stemmer = SnowballStemmer('russian')

In [2]:
dbf = Dbf5('settlement-point.dbf')
df = dbf.to_dataframe()  # в таблице куча данных. Именно ее надо сравнить с остальными.
df

,NAME,NAME_EN,INT_NAME,NAME_RU,OFFICIAL_S,PLACE,A_CNTR,A_PLACE,A_DSTRCT,A_PSTCD,POPULATION,OSM_TYPE,OSM_ID,oktmo
0,Новосибирск,Novosibirsk,NaN,Новосибирск,ru:город,city,NaN,NaN,NaN,NaN,1625600,node,54,50701000001
1,Сочи,Sochi,Sochi,Сочи,ru:город,city,RU,Краснодарский край,NaN,NaN,389946,node,34043670,03726000001
2,Тула,Tula,Tula,Тула,ru:город,city,RU,Тульская область,NaN,NaN,479105,node,34389350,70701000001
3,Магас,Magas,Magas,Магас,ru:город,town,RU,Ингушетия,городской округ Магас,NaN,6880,node,34395341,NaN
4,Геленджик,Gelendzhik,NaN,Геленджик,ru:город,town,RU,Краснодарский край,NaN,NaN,69341,node,34181150,03708000001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179374,Великий Новгород,Veliky Novgorod,Velikiy Novgorod,Великий Новгород,ru:город,city,RU,Новгородская область,NaN,NaN,224297,node,27017589,49701000001
179375,Ледмозеро,Ledmozero,Ledmozero,Ледмозеро,NaN,village,RU,Республика Карелия,Муезерский район,NaN,2046,node,26898771,86627427101
179376,Сегежа,Segezha,Segezha,Сегежа,ru:город,town,RU,NaN,Сегежский район,186420,26241,node,26898825,86645101001
179377,Апатиты,Apatity,Apatiitti,Апатиты,ru:город,town,RU,Мурманская область,городской округ Апатиты,184209,55713,node,26898767,47705000001
179378,Невель,Nevel,NaN,Невель,ru:город,town,RU,Псковская область,Невельский район,NaN,16272,node,26163795,58620101001

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179379 entries, 0 to 179378
Data columns (total 14 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   NAME        177861 non-null  object
 1   NAME_EN     30029 non-null   object
 2   INT_NAME    4602 non-null    object
 3   NAME_RU     43176 non-null   object
 4   OFFICIAL_S  51588 non-null   object
 5   PLACE       179379 non-null  object
 6   A_CNTR      83016 non-null   object
 7   A_PLACE     83428 non-null   object
 8   A_DSTRCT    79170 non-null   object
 9   A_PSTCD     30927 non-null   object
 10  POPULATION  60378 non-null   object
 11  OSM_TYPE    179379 non-null  object
 12  OSM_ID      179379 non-null  int64
 13  oktmo       154707 non-null  object
dtypes: int64(1), object(13)
memory usage: 19.2+ MB

In [4]:
# df.to_excel('Файл_dbf.xlsx')

In [5]:
nas = pd.concat(pd.read_excel('Населенные пункты.xlsx', sheet_name=None), ignore_index=True)     
# в таблице код, КЧ (что это???), наименование нас пункта и доп данные. Взяты данные со всех листов
nas

,Код,КЧ,Наименование,Дополнительные данные
0,14000000000,9,"Населенные пункты, входящие в состав муниципал...",NaN
1,14610160000,2,"Населенные пункты, входящие в состав городског...",NaN
2,14610160051,9,п Октябрьский,NaN
3,14610165000,9,"Населенные пункты, входящие в состав городског...",NaN
4,14610165051,5,п Разумное,NaN
...,...,...,...,...
174771,77715000116,8,с Конергино,NaN
174772,77715000121,2,с Нутэпэльмен,NaN
174773,77715000126,7,с Рыркайпий,NaN
174774,77715000131,1,с Ушаковское,NaN
174775,77715000136,6,с Уэлькаль,NaN

In [6]:
nas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174776 entries, 0 to 174775
Data columns (total 4 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Код                    174776 non-null  int64
 1   КЧ                     174776 non-null  int64
 2   Наименование           174776 non-null  object
 3   Дополнительные данные  3 non-null       object
dtypes: int64(2), object(2)
memory usage: 5.3+ MB

In [7]:
nas.columns = ['oktmo', 'КЧ', 'Наименование', 'Дополнительные данные']

In [8]:
# nas.to_excel('Население.xlsx')

In [9]:
region = pd.read_excel('Справочник регионов.xlsx')  # в таблице только код региона и название региона
region

    Код                             Регион
0     1                     Алтайский край
1     3                 Краснодарский край
2     4                  Красноярский край
3     5                    Приморский край
4     7                Ставропольский край
..  ...                                ...
80   98           Республика Саха (Якутия)
81   99       Еврейская автономная область
82  118          Ненецкий автономный округ
83  718  Ханты-Мансийский автономный округ
84  719    Ямало-Ненецкий автономный округ

[85 rows x 2 columns]

Начнем с кода ОКТМО:

In [10]:
df['oktmo'].isna().sum()

24672

In [11]:
df['oktmo'] = df['oktmo'].fillna(0)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179379 entries, 0 to 179378
Data columns (total 14 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   NAME        177861 non-null  object
 1   NAME_EN     30029 non-null   object
 2   INT_NAME    4602 non-null    object
 3   NAME_RU     43176 non-null   object
 4   OFFICIAL_S  51588 non-null   object
 5   PLACE       179379 non-null  object
 6   A_CNTR      83016 non-null   object
 7   A_PLACE     83428 non-null   object
 8   A_DSTRCT    79170 non-null   object
 9   A_PSTCD     30927 non-null   object
 10  POPULATION  60378 non-null   object
 11  OSM_TYPE    179379 non-null  object
 12  OSM_ID      179379 non-null  int64
 13  oktmo       179379 non-null  object
dtypes: int64(1), object(13)
memory usage: 19.2+ MB

In [13]:
df.head(20)

,NAME,NAME_EN,INT_NAME,NAME_RU,OFFICIAL_S,PLACE,A_CNTR,A_PLACE,A_DSTRCT,A_PSTCD,POPULATION,OSM_TYPE,OSM_ID,oktmo
0,Новосибирск,Novosibirsk,NaN,Новосибирск,ru:город,city,NaN,NaN,NaN,NaN,1625600,node,54,50701000001
1,Сочи,Sochi,Sochi,Сочи,ru:город,city,RU,Краснодарский край,NaN,NaN,389946,node,34043670,03726000001
2,Тула,Tula,Tula,Тула,ru:город,city,RU,Тульская область,NaN,NaN,479105,node,34389350,70701000001
3,Магас,Magas,Magas,Магас,ru:город,town,RU,Ингушетия,городской округ Магас,NaN,6880,node,34395341,0
4,Геленджик,Gelendzhik,NaN,Геленджик,ru:город,town,RU,Краснодарский край,NaN,NaN,69341,node,34181150,03708000001
5,Кабардинка,Kabardinka,NaN,Кабардинка,ru:село,town,RU,Краснодарский край,городской округ Геленджик,NaN,7550,node,34181855,03708000151
6,Дубна,Dubna,NaN,Дубна,ru:город,town,RU,Московская область,городской округ Дубна,141980,75176,node,34389205,46718000001
7,Тарское,Tarskoye,Tarskoye,Тарское,NaN,village,RU,NaN,Пригородный район,NaN,4371,node,34395346,90640475101
8,Нижний Тагил,Nizhny Tagil,Nizhny Tagil,Нижний Тагил,ru:город,city,RU,Свердловская область,городской округ Нижний Тагил,NaN,353950,node,34506055,65751000001
9,Дивноморское,Divnomorskoye,Divnomorskoe,Дивноморское,ru:село,village,RU,Краснодарский край,городской округ Геленджик,NaN,6358,node,36722773,03708000146
10,Усть-Луга,Ust-Luga,NaN,Усть-Луга,ru:посёлок,village,RU,Ленинградская область,Кингисеппский район,NaN,2365,node,34390262,41621428101
11,Абрамцево,Abramtsevo,NaN,NaN,ru:село,village,RU,Московская область,NaN,141352,209,node,34389232,46615106106
12,Колпино,Kolpino,NaN,Колпино,ru:город,city,RU,Санкт-Петербург,NaN,NaN,147965,node,60081897,0
13,Победа,NaN,NaN,NaN,ru:посёлок,village,RU,Ленинградская область,Выборгский район,NaN,2354,node,60211797,41615158146
14,Неман,NaN,NaN,Неман,ru:город,town,RU,Калининградская область,NaN,NaN,11346,node,60238408,27714000001
15,Торжок,Torzhok,Torzhok,Торжок,ru:город,town,RU,Тверская область,NaN,172000,46690,node,60405981,28750000001
16,Елионка,NaN,NaN,NaN,NaN,village,RU,Брянская область,Стародубский муниципальный округ,NaN,460,node,60078362,15650412136
17,Мишковка,NaN,NaN,Мишковка,NaN,village,RU,Брянская область,Стародубский муниципальный округ,NaN,557,node,60565325,15650448237
18,Ершичи,Yershichi,NaN,Петровка Ершичиский район Смоленска область,ru:село,village,RU,Смоленская область,Ершичский район,NaN,3169,node,60699747,66621433101
19,Светлый,NaN,NaN,Светлый,ru:город,town,RU,Калининградская область,NaN,NaN,21849,node,60237889,27725000001

Идем дальше: сравним 2 столбца и посмотрим, какие ОКТМО есть в файле nas, а какие - нет. Сделаем новый столбец в df, где пропишем, есть ли (True) или нет (False) ОКТМО файла df в справочнике К+:

In [14]:
# set_oktmo = set(df['oktmo']).intersection(set(nas['Код']))

In [15]:
df['Сравним ОКТМО и К+'] = df['oktmo'].isin(nas['oktmo'])

In [16]:
df['Сравним регион со справочником регионов'] = df['A_PLACE'].isin(region['Регион'])

In [17]:
df['Сравним регион со справочником регионов'].value_counts()

False    103949
True      75430
Name: Сравним регион со справочником регионов, dtype: int64

In [40]:
df.head(20)

,NAME,NAME_EN,INT_NAME,NAME_RU,OFFICIAL_S,PLACE,A_CNTR,A_PLACE,A_DSTRCT,A_PSTCD,POPULATION,OSM_TYPE,OSM_ID,oktmo,Сравним ОКТМО и К+,Сравним регион со справочником регионов
0,Новосибирск,Novosibirsk,NaN,Новосибирск,ru:город,city,NaN,NaN,NaN,NaN,1625600,node,54,50701000001,False,False
1,Сочи,Sochi,Sochi,Сочи,ru:город,city,RU,Краснодарский край,NaN,NaN,389946,node,34043670,03726000001,False,True
2,Тула,Tula,Tula,Тула,ru:город,city,RU,Тульская область,NaN,NaN,479105,node,34389350,70701000001,False,True
3,Магас,Magas,Magas,Магас,ru:город,town,RU,Ингушетия,городской округ Магас,NaN,6880,node,34395341,0,False,False
4,Геленджик,Gelendzhik,NaN,Геленджик,ru:город,town,RU,Краснодарский край,NaN,NaN,69341,node,34181150,03708000001,False,True
5,Кабардинка,Kabardinka,NaN,Кабардинка,ru:село,town,RU,Краснодарский край,городской округ Геленджик,NaN,7550,node,34181855,03708000151,False,True
6,Дубна,Dubna,NaN,Дубна,ru:город,town,RU,Московская область,городской округ Дубна,141980,75176,node,34389205,46718000001,False,True
7,Тарское,Tarskoye,Tarskoye,Тарское,NaN,village,RU,NaN,Пригородный район,NaN,4371,node,34395346,90640475101,False,False
8,Нижний Тагил,Nizhny Tagil,Nizhny Tagil,Нижний Тагил,ru:город,city,RU,Свердловская область,городской округ Нижний Тагил,NaN,353950,node,34506055,65751000001,False,True
9,Дивноморское,Divnomorskoye,Divnomorskoe,Дивноморское,ru:село,village,RU,Краснодарский край,городской округ Геленджик,NaN,6358,node,36722773,03708000146,False,True
10,Усть-Луга,Ust-Luga,NaN,Усть-Луга,ru:посёлок,village,RU,Ленинградская область,Кингисеппский район,NaN,2365,node,34390262,41621428101,False,True
11,Абрамцево,Abramtsevo,NaN,NaN,ru:село,village,RU,Московская область,NaN,141352,209,node,34389232,46615106106,False,True
12,Колпино,Kolpino,NaN,Колпино,ru:город,city,RU,Санкт-Петербург,NaN,NaN,147965,node,60081897,0,False,True
13,Победа,NaN,NaN,NaN,ru:посёлок,village,RU,Ленинградская область,Выборгский район,NaN,2354,node,60211797,41615158146,False,True
14,Неман,NaN,NaN,Неман,ru:город,town,RU,Калининградская область,NaN,NaN,11346,node,60238408,27714000001,False,True
15,Торжок,Torzhok,Torzhok,Торжок,ru:город,town,RU,Тверская область,NaN,172000,46690,node,60405981,28750000001,False,True
16,Елионка,NaN,NaN,NaN,NaN,village,RU,Брянская область,Стародубский муниципальный округ,NaN,460,node,60078362,15650412136,False,True
17,Мишковка,NaN,NaN,Мишковка,NaN,village,RU,Брянская область,Стародубский муниципальный округ,NaN,557,node,60565325,15650448237,False,True
18,Ершичи,Yershichi,NaN,Петровка Ершичиский район Смоленска область,ru:село,village,RU,Смоленская область,Ершичский район,NaN,3169,node,60699747,66621433101,False,True
19,Светлый,NaN,NaN,Светлый,ru:город,town,RU,Калининградская область,NaN,NaN,21849,node,60237889,27725000001,False,True

Буду завтра решать лемматизацией!!!!!!!!!!!!!!!!!!!!!

In [42]:
nas_new = pd.read_excel('Население_без_примеси.xlsx')

In [43]:
nas_new

,Unnamed: 0,oktmo,КЧ,Наименование,Дополнительные данные
0,0,14000000000,9,Белгородской области,NaN
1,1,14610160000,2,поселок Октябрьский Белгородского муниципал...,NaN
2,2,14610160051,9,п Октябрьский,NaN
3,3,14610165000,9,поселок Разумное Белгородского муниципально...,NaN
4,4,14610165051,5,п Разумное,NaN
...,...,...,...,...,...
174771,174771,77715000116,8,с Конергино,NaN
174772,174772,77715000121,2,с Нутэпэльмен,NaN
174773,174773,77715000126,7,с Рыркайпий,NaN
174774,174774,77715000131,1,с Ушаковское,NaN
174775,174775,77715000136,6,с Уэлькаль,NaN

Пролемматизируем столбец "Наименование" таблицы nas_new:

In [ ]:
%%time
m = Mystem()
purpose_lemmatized = []
for row in nas_new['Наименование']:
    lemmas = ' '.join(m.lemmatize(row)).strip()
    purpose_lemmatized.append(lemmas.split())
nas_new['Наименование_new'] = purpose_lemmatized
print(nas_new)

Переходим к плотности населения в регионах по ОКТМО: